runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: mBa8aAIlP84o4P0R3mppHrSKa1Vkwujm
  STORAGE_DIR: /tmp
  APP_DEBUG: true
  APP_TIMEZONE: EST
  APP_ENV: local
  DB_CONNECTION: mysql
  DB_HOST: 35.196.225.149
  DB_PORT: 3306
  DB_DATABASE: mendoza
  DB_USERNAME: mlb
  DB_PASSWORD: Ls7LHDvo61gV
  CACHE_DRIVER: file
  QUEUE_DRIVER: sync
  PAGE_TITLE: CopaMendoza
  ADMIN_USER: admin
  ADMIN_PASS: alita
  LANGUAGES: en,es
  SITE_URL: https://copa-176119.appspot.com